<a href="https://colab.research.google.com/github/yash83085/SL-3/blob/main/SIMPLE_LINEAR_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4) Data Analytics I
Create a Linear Regression Model using Python/R to predict home prices using Boston Housing Dataset (https://www.kaggle.com/c/boston-housing). The Boston Housing dataset contains
information about various houses in Boston through different parameters. There are 506 samples and 13 feature variables in this dataset.

The objective is to predict the value of prices of the house using the given features.

In [1]:
#import dependencies
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Load the Boston Housing Data set from sklearn.datasets and print it
df = pd.read_csv("/content/drive/MyDrive/SL-3_Datasets/BostonHousing.csv")
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
df.shape

(506, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [6]:
df1 = df[['rm','tax','ptratio','lstat','medv']]
df1.head()

rm  tax  ptratio  lstat  medv
0  6.575  296     15.3   4.98  24.0
1  6.421  242     17.8   9.14  21.6
2  7.185  242     17.8   4.03  34.7
3  6.998  222     18.7   2.94  33.4
4  7.147  222     18.7   5.33  36.2

In [7]:
df_x = df.iloc[:,0:3].values
df_y = df.iloc[:,-1:].values

In [8]:
print(f"Shape of Dependent Variable X = {df_x.shape}")
print(f"Shape of Independent Variable y = {df_y.shape}")

Shape of Dependent Variable X = (506, 3)
Shape of Independent Variable y = (506, 1)


In [9]:
# Intialise the linear regression model
reg = linear_model.LinearRegression()

In [10]:
# Split the data into 67% training and 33% testing data
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size= 0.33, random_state= 42)


In [11]:
# Train the model with our training data
reg.fit(x_train, y_train)

LinearRegression()

In [12]:
# Print the co-efficients/weights for each feature/coloum of our model
print(reg.coef_) #f(x) = mx + da + b = y

[[-0.27930998  0.04925681 -0.39841919]]


In [13]:
# print the predictions on our test data
y_pred = reg.predict(x_test)
print(y_pred)

[[26.17742954]
 [27.21730341]
 [16.73497983]
 [23.48415493]
 [19.18353976]
 [22.6765858 ]
 [23.78341637]
 [19.01401504]
 [19.47730682]
 [23.89330882]
 [22.25170298]
 [25.24931955]
 [ 7.82793283]
 [22.6891743 ]
 [24.79702702]
 [19.30735228]
 [17.56970093]
 [16.60172959]
 [31.5700769 ]
 [17.9995671 ]
 [25.983522  ]
 [27.21078432]
 [24.25768361]
 [23.04602823]
 [18.64379557]
 [18.3552125 ]
 [22.68151842]
 [17.94802324]
 [23.5486747 ]
 [23.88101918]
 [26.16420141]
 [24.82951636]
 [15.12825773]
 [19.57791148]
 [19.3700881 ]
 [19.41532721]
 [24.99221629]
 [25.73929478]
 [23.55945328]
 [23.45517652]
 [23.87509222]
 [28.5598076 ]
 [31.42268436]
 [25.97611028]
 [26.44497001]
 [18.66067706]
 [24.25184324]
 [23.485099  ]
 [19.39061459]
 [27.78117131]
 [25.26400287]
 [27.46471416]
 [24.22928896]
 [24.37426336]
 [27.06910727]
 [19.57918234]
 [19.02260135]
 [29.77525058]
 [26.01362987]
 [26.51213529]
 [26.96885938]
 [31.76004192]
 [25.22306979]
 [24.34932522]
 [30.07653726]
 [23.47570497]
 [18.17059

In [14]:
# Print the actual values
print(y_test)

[[23.6]
 [32.4]
 [13.6]
 [22.8]
 [16.1]
 [20. ]
 [17.8]
 [14. ]
 [19.6]
 [16.8]
 [21.5]
 [18.9]
 [ 7. ]
 [21.2]
 [18.5]
 [29.8]
 [18.8]
 [10.2]
 [50. ]
 [14.1]
 [25.2]
 [29.1]
 [12.7]
 [22.4]
 [14.2]
 [13.8]
 [20.3]
 [14.9]
 [21.7]
 [18.3]
 [23.1]
 [23.8]
 [15. ]
 [20.8]
 [19.1]
 [19.4]
 [34.7]
 [19.5]
 [24.4]
 [23.4]
 [19.7]
 [28.2]
 [50. ]
 [17.4]
 [22.6]
 [15.1]
 [13.1]
 [24.2]
 [19.9]
 [24. ]
 [18.9]
 [35.4]
 [15.2]
 [26.5]
 [43.5]
 [21.2]
 [18.4]
 [28.5]
 [23.9]
 [18.5]
 [25. ]
 [35.4]
 [31.5]
 [20.2]
 [24.1]
 [20. ]
 [13.1]
 [24.8]
 [30.8]
 [12.7]
 [20. ]
 [23.7]
 [10.8]
 [20.6]
 [20.8]
 [ 5. ]
 [20.1]
 [48.5]
 [10.9]
 [ 7. ]
 [20.9]
 [17.2]
 [20.9]
 [ 9.7]
 [19.4]
 [29. ]
 [16.4]
 [25. ]
 [25. ]
 [17.1]
 [23.2]
 [10.4]
 [19.6]
 [17.2]
 [27.5]
 [23. ]
 [50. ]
 [17.9]
 [ 9.6]
 [17.2]
 [22.5]
 [21.4]
 [12. ]
 [19.9]
 [19.4]
 [13.4]
 [18.2]
 [24.6]
 [21.1]
 [24.7]
 [ 8.7]
 [27.5]
 [20.7]
 [36.2]
 [31.6]
 [11.7]
 [39.8]
 [13.9]
 [21.8]
 [23.7]
 [17.6]
 [24.4]
 [ 8.8]
 [19.2]
 [25.3]


In [15]:
# Check the model performance/accuracy using Mean Squared error(MSE)
print( np.mean((y_pred - y_test)**2 ))


49.17549394985065


In [16]:
# Check the model performance/accuracy using Mean Squared error (MSE) and sklearn.metrics
from sklearn.metrics import mean_squared_error
print( mean_squared_error(y_test, y_pred))

49.17549394985065


In [17]:
from sklearn import metrics
mse = metrics.mean_squared_error(y_test,y_pred)
mae = metrics.mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print(f'Mean Squared Error: {mse}',f'Mean Absolute Error: {mae}',f'Root Mean Squared Error: {rmse}',sep='\n')

Mean Squared Error: 49.17549394985065
Mean Absolute Error: 5.158028841813329
Root Mean Squared Error: 7.012524078379386
